server:
  port: 5551 #服务端口

eureka:
  client:
    registerWithEureka: true #是否注册
    fetchRegistry: true #启用客户端缓存
    serviceUrl:
      defaultZone: http://peer1:8881/eureka/,http://peer2:8882/eureka/ #注册到两个服务中心

spring:
  application:
    name: apigateway #服务名

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #设置超时时间 10秒

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000