server:
  port: 6661 #服务端口

eureka:
  client:
    registerWithEureka: true #是否注册
    fetchRegistry: true #启用客户端缓存
    serviceUrl:
      defaultZone: http://peer1:8881/eureka/,http://peer2:8882/eureka/ #注册到两个服务中心

spring:
  application:
    name: orderservice #服务名